export * from './0_main.seeder'
export * from './1_location.seeder'
export * from './2_episode.seeder'
export * from './3_character.seeder'
export * from './4_character-to-episode.seeder'
export * from './5_role.seeder'
