import { ApiProperty } from '@nestjs/swagger'
import { Column, Entity, JoinTable, ManyToMany, PrimaryGeneratedColumn } from 'typeorm'
import { User } from '../../user/entities/user.entity'

@Entity('roles')
export class Role {
  @ApiProperty({ example: 1, description: 'Autogenerated primary id' })
  @PrimaryGeneratedColumn()
  id: number

  @ApiProperty({ example: 'admin', description: 'The role of the user.' })
  @Column()
  value: string

  @ManyToMany(() => User, user => user.roles)
  @JoinTable()
  users?: User[]
}
