import { ApiProperty } from '@nestjs/swagger'
import { Column, CreateDateColumn, Entity, OneToMany, PrimaryGeneratedColumn } from 'typeorm'

import { Character } from '@infrastructure/entities/main'

@Entity('locations')
export class Location {
  @ApiProperty({ example: 1, description: 'The id of the location.' })
  @PrimaryGeneratedColumn()
  public id: number

  @ApiProperty({ example: 'Earth (C-137)', description: 'The name of the location.' })
  @Column()
  public name: string

  @ApiProperty({ example: 'Planet', description: 'The type of the location.' })
  @Column()
  public type: string

  @ApiProperty({ example: 'Dimension C-137', description: 'The dimension in which the location is located.' })
  @Column()
  public dimension: string

  @OneToMany(() => Character, character => character.location)
  public residents: Character[]

  @ApiProperty({
    description: 'Autogenerated date of created.'
  })
  @CreateDateColumn({ name: 'created_at' })
  public createdAt: Date
}
