import { Column, CreateDateColumn, Entity, ManyToMany, PrimaryGeneratedColumn } from 'typeorm'
import { Character } from 'src/character/entities/character.entity'
import { ApiProperty } from '@nestjs/swagger'

@Entity('episodes')
export class Episode {
  @ApiProperty({ example: 1, description: 'The id of the episode.' })
  @PrimaryGeneratedColumn('increment')
  id: number

  @ApiProperty({ example: 'Pilot', description: 'The name of the episode.' })
  @Column()
  name: string

  @ApiProperty({ example: 'S01E01', description: 'The code of the episode.' })
  @Column()
  episode: string

  @ApiProperty({ example: 'December, 2, 2013', description: 'The air date of the episode.' })
  @Column({ name: 'air_date', select: false })
  airDate: string

  @ApiProperty({
    description: 'Autogenerated date of created.'
  })
  @CreateDateColumn({ name: 'created_at', select: false })
  createdAt: Date

  @ApiProperty({
    example: [1, 2, 3, 4, 5, 7, 10],
    description: 'List of characters who have been seen in the episode.'
  })
  @ManyToMany(() => Character, character => character.episodes, { onDelete: 'CASCADE' })
  characters: Character[]
}
