export const enum HttpStack {
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',

  CHARACTERS_NOT_FOUND = 'CHARACTERS_NOT_FOUND',
}
