export const enum HttpStack {
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  PASSWORD_IS_EQUAL_OLD = 'PASSWORD_IS_EQUAL_OLD',
  PASSWORDS_DONT_MATCH = 'PASSWORDS_DONT_MATCH',

  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  ID_NOT_FOUND = 'ID_NOT_FOUND',
  INVALID_LINK = 'INVALID_LINK',
  ALREADY_VERIFIED = 'ALREADY_VERIFIED',

  CHARACTERS_NOT_FOUND = 'CHARACTERS_NOT_FOUND',
  CHARACTER_EXIST = 'CHARACTER_EXIST',
  EMPTY_FILE = 'EMPTY_FILE'
}
